version: '3.8'

services:
  craigybabyj-fileserver:
    image: ghcr.io/craigybabyj/craigybabyj-fileserver:latest
    container_name: craigybabyj-fileserver
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /opt/craigybabyj-fileserver/data:/app/data
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/data/uploads
      - SECRET_KEY=your-secret-key-change-this
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
