version: '3.8'

services:
  app:
    image: ghcr.io/craigybabyj/craigybabyj-fileserver:latest
    container_name: craigybabyj-fileserver
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./data/logs:/app/data/logs
      - ./.env:/app/.env:ro
    networks:
      - fileserver-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: craigybabyj-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./data/logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - fileserver-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

networks:
  fileserver-network:
    driver: bridge

volumes:
  uploads:
    driver: local
  logs:
    driver: local